---
- name: check if reboot is needed
  shell: needs-restarting | grep -v 'Updating Subscription Management' | wc -l
  register: needs_restarting
  changed_when: needs_restarting.stdout|int != 0

- name: reboot host if needed
  block:
  - name: reboot host 
    shell: sleep 5 ; shutdown -r now "Ansible reboot"
    async: 10 # do not care for 10 sec (we left in 5 sec)
    poll: 0  # fire and forget

  - name: wait for host to finish reboot
    wait_for_connection:
      delay: 20  # do not check for at least xx sec

  - name: check if host has booted within last 300 sec
    shell: test $(cat /proc/uptime | cut -d. -f1) -lt 300
    changed_when: false
    register: reboot_check

  - name: alert if host has not been rebootet
    fail:
      msg: "{{ ansible_host }} has not booted, manual check needed"
    when: reboot_check.rc != 0
  when: needs_restarting.stdout|int != 0
  throttle: "{{ os_update_conc_reboot }}"
...
